### ISSUE TITLE
NUnit tutorial code does not compile

### ISSUE THREAD

**Issue by kevinpohlmeier** [csf-dev/CSF.Screenplay#185]
The NUnit code has the following line which generates a compiler error. The only parameterless "Should" method on IThenActor is a void method.

`var theText = Then(joe).Should<ReadTheTopToDoItem>();`

**Comment by craigfowler** [comment]
Thanks, good spot.  I have corrected the examples so that it at least compiles.

Please note that [the tutorial isn't complete] yet.  I've updated the linked issue with things that I know I still need to do.  At the moment I'm spending most of my spare-time dev effort on a project which uses Screenplay, which will shake out anything else I need to improve.  Sorry that it means I haven't put as much effort into documenting it as I should.

There are [quite a few examples of Screnplay] in-use in that other project's repository though.  They use SpecFlow to drive them (and not NUnit) but the Screenplay parts (Actions/Tasks etc) are all the same.  SpecFlow just means that they are driven by bindings and `.feature` files instead of test methods.

[the tutorial isn't complete]: https://github.com/csf-dev/CSF.Screenplay/issues/154
[quite a few examples of Screnplay]: https://github.com/csf-dev/agiil/tree/master/Tests/Agiil.BDD
